name: Deploy Test Environment
concurrency:
  group: Test
  cancel-in-progress: true
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    types: [opened, ready_for_review, synchronize, labeled, reopened]
jobs:
  deploy:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'ready for test') }}
    timeout-minutes: 15
    name: Build & Upload Mobile Application
    runs-on: macos-latest
    environment:
      name: Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.1.0
      - name: Send slack notification
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "attachments": [
                {
                  "pretext": "*Pull Request:* <https://github.com/waveneuroscience/sonal-mobile-app-ios/pull/${{ github.event.number }}|${{ github.event.pull_request.title }}>",
                  "color": "dbab09",
                  "fields": [
                    {
                      "title": "OS",
                      "short": true,
                      "value": ":apple: iOS"
                    },
                    {
                      "title": "Build result",
                      "short": true,
                      "value": "${{job.status}}"
                    },
                    {
                      "title": "App Name",
                      "short": true,
                      "value": "Sonal"
                    },
                    {
                      "title": "Version (Build)",
                      "short": true,
                      "value": "${{ env.FL_BUILD_VERSION }} (${{ env.FL_BUILD_NUMBER }})"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.WEBHOOK_URL_SLACK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
