name: Deploy Test Environment
concurrency:
  group: Test
  cancel-in-progress: true
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    types: [opened, ready_for_review, synchronize, labeled, reopened]
jobs:
  deploy:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'ready for test') }}
    timeout-minutes: 15
    name: Build & Upload Mobile Application
    runs-on: macos-latest
    environment:
      name: Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.1.0
      - name: Bundle Install
        run: bundle install
      - name: Specs Repo
        run: pod repo add waveneuro-pod-specs https://${POD_GITHUB_USER}:${POD_GITHUB_API_TOKEN}@github.com/waveneuroscience/specs.git
        env:
          POD_GITHUB_API_TOKEN: ${{ secrets.POD_GITHUB_API_TOKEN }}
          POD_GITHUB_USER: ${{ secrets.POD_GITHUB_USER }}
      - name: Run Fastlane
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_URL: ${{ secrets.GIT_URL }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          APP_STORE_CONNECT_KEY_CONTENT: ${{ secrets.ASC_PRIVATE_KEY }}
        run: |
          sudo xcode-select --switch /Applications/Xcode_14.2.app
          fastlane ios beta --env qa
      - name: Send slack notification
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "* Pull Request:* <https://github.com/waveneuroscience/sonal-mobile-app-ios/pull/${{ github.event.number }}|${{ github.event.pull_request.title }}>"
                }
              }
              ],
              "attachments": [
                {
                  "pretext": "Build result: *${{job.status}}*",
                  "color": "dbab09",
                  "fields": [
                    {
                      "title": "OS",
                      "short": true,
                      "value": ":apple: iOS"
                    },
                    {
                      "title": "App Name",
                      "short": true,
                      "value": "Sonal"
                    },
                    {
                      "title": "Version (Build)",
                      "short": true,
                      "value": "${{ env.FL_BUILD_VERSION }} (${{ env.FL_BUILD_NUMBER }})"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.WEBHOOK_URL_SLACK }}

